### ISSUE TITLE
cdn.nuclei.sh is down

### ISSUE THREAD

**Issue by wawaloll** [ivre/ivre#1612]
ivre version:
```
IVRE - Network recon framework
Copyright 2011 - 2023 Pierre LALET <pierre@droids-corp.org>
Version 0.9.20.dev173

Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

Linux vps2809181 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64

Dependencies:
    MySQLdb: *missing*
    OpenSSL: 21.0.0
    PIL: *missing*
    bottle: 0.12.19
    cryptography: 3.4.8
    dbus: 1.2.18
    krbV: *missing*
    matplotlib: *missing*
    psycopg2: *missing*
    pycurl: *missing*
    pymongo: 3.11.0
    sqlalchemy: *missing*
    tinydb: *missing*
    elasticsearch: *missing*
    elasticsearch_dsl: *missing*

```

command that i ran:
`ivre getwebdata`

output:
```
ERROR:ivre:Cannot download https://cdn.nuclei.sh/ [<urlopen error [Errno -5] No address associated with hostname>]
ERROR:ivre:Cannot download https://support.censys.io/hc/en-us/articles/360043177092-from-faq [HTTP Error 403: Forbidden]
```
