### ISSUE TITLE
Using sqlite with a modified docker-compose.yml

### ISSUE THREAD

**Issue by dcunited001** [ivre/ivre#1706]
Mainly I'm trying to extract the schema from the sqlite databases, so I can use it to generate diagrams to understand the data model.

I also want to explore running it in my homelab, so I want to build/run the application using docker/etc, since later I would want scans to & from many nodes.

Questions

+ do the `sqlite:///data/ivre.sqlite` url's require separate files when used as a backend for separate purposes.
  - I tried using the `--to-db=sqlite://data/ivre.sqlite` parameter
+ do i have mongodb setup correctly?
+ Are there reference schemas that someone can link to?

There's more information in my notes [here](https://github.com/dcunited001/zettelkasten/blob/master/slips/20250519174503-ivre_running_and_extracting_schema.org?plain=1#L33) but it's probably TMI. I tried to consolidate everything for Github (but I had to convert from org, =C-w= cuts text in emacs and closes tabs in the browsers, so I lost the text once already)

## Failures

Mongo

+ From =mongo= container does record data into `./data/var_lib_mongodb` but there's not an `ivre` database when i connect from the host to `localhost:27017`.
  - From host, `mongosh localhost:27017` succeeds, but `show dbs` does not list `ivre` database (because other containers via `docker-compose.yml` cannot connect, they also cannot init the local)
+ from the docker compose containers, mongodb also doesn't accept connections (always times out, even when port mapping is set).

IVRE

+ ivre ipinfo --init :: only succeeds from `ivre/base`, not `ivre/client`
  - `File "/usr/local/lib/python3.11/dist-packages/sqlalchemy/engine/default.py", line 598, in connect`
    - `return self.dbapi.connect(*cargs, **cparams)`
  - `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open
    database file`
  - in ivre/base, its fine
+ ivre scancli --init :: fails
  - `ivre:Cannot get database for DBNmap from sqlite:/data/ivre.sqlite`
  - modulename, classname = cls.backends[db_type] :: swallows the error, no
    `cls.backend[db_type]`
+ ivre view --init :: fails
  - `ivre:Cannot get database for DBView from sqlite:/data/ivre.sqlite`
  - modulename, classname = cls.backends[db_type] :: swallows the error, no
    `cls.backend[db_type]`
+ ivre flowcli --init :: timeout if run from `ivre/base` or `ivre/client` when
  trying to reach `localhost:27017`
+ ivre runscansagentdb --init :: same timeout for `mongodb`

### Config

```sh
DB="mongodb:///ivre"
DB_PASSIVE="sqlite:///data/ivre.passive.sqlite"
# DB_NMAP="sqlite:///data/ivre.nmap.sqlite" # fails 
# DB_VIEW="sqlite:///data/ivre.view.sqlite" # fails 
DB_DATA = "maxmind:///share/data/ivre/geoip"
# DB_DATA = "maxmind:///$shareData/ivre/geoip"

DEBUG = True
IPDATA_URLS = {
'GeoLite2-City.tar.gz':
'https://ivre.rocks/data/tests/db/GeoLite2-City.tar.gz',
'GeoLite2-City-CSV.zip':
'https://ivre.rocks/data/tests/db/GeoLite2-City-CSV.zip',
'GeoLite2-Country.tar.gz':
'https://ivre.rocks/data/tests/db/GeoLite2-Country.tar.gz',
'GeoLite2-Country-CSV.zip':
'https://ivre.rocks/data/tests/db/GeoLite2-Country-CSV.zip',
'GeoLite2-ASN.tar.gz':
'https://ivre.rocks/data/tests/db/GeoLite2-ASN.tar.gz',
'GeoLite2-ASN-CSV.zip':
'https://ivre.rocks/data/tests/db/GeoLite2-ASN-CSV.zip',
'iso3166.csv': 'https://ivre.rocks/data/tests/db/iso3166.csv',
'BGP.raw': 'https://ivre.rocks/data/tests/db/data-raw-table',
}
NMAP_SCAN_TEMPLATES["default"]["pings"] = []
NMAP_SCAN_TEMPLATES["default"]["scans"] = "T"
NMAP_SCAN_TEMPLATES["default"]["osdetect"] = False
NMAP_SCAN_TEMPLATES["default"]["traceroute"] = False
NMAP_SCAN_TEMPLATES["http"] = NMAP_SCAN_TEMPLATES["default"].copy()
NMAP_SCAN_TEMPLATES["http"]["ports"] = "T:80"
NMAP_SCAN_TEMPLATES["http"]['scripts_categories'] = []
NMAP_SCAN_TEMPLATES["http"]['scripts_exclude'] = []
NMAP_SCAN_TEMPLATES["http"]['scripts_force'] = ["http-title", "http-screenshot"]
NMAP_SCAN_TEMPLATES["http"]['extra_options'] = ["--open"]
AGENT_MASTER_PATH = "/tmp/var_lib/ivre/master"
```

### Python

```sh
diff /data/ecto/hacknet/ivre/ivre/requirements-{sqlite,all}.txt && echo
```

```diff
1,4c1
> bandit
> black
> bottle
> codespell
---
< sqlalchemy<2
6,14d2
> docutils!=0.18
> elasticsearch
> elasticsearch-dsl
> flake8
> mypy
> psycopg2
> pylint
> pymongo>=3.7
> pymongo[srv]>=3.7
16,22c4
> rstcheck[sphinx]
> Sphinx
> sphinxcontrib-httpdomain
> sphinx_rtd_theme
> sphinx-lint
> sqlalchemy<2
> tinydb
---
< bottle
```

### Images

I built the images with these commands (after generating the tar)

``` shell
docker pull debian:12
docker build -t ivre/base docker/base-local
for img in client agent web web-doku web-uwsgi ; do
docker build -t "ivre/$img" "docker/$img";
done
```

I made these changes to the `./docker/base-local/Dockerfile`, where I basically
added `build-essential python3.11-dev libpq-dev`

```diff
diff --git a/docker/base-local/Dockerfile b/docker/base-local/Dockerfile
index 23e639b3..f35496ed 100644
--- a/docker/base-local/Dockerfile
+++ b/docker/base-local/Dockerfile
@@ -13,7 +13,7 @@
#
# You should have received a copy of the GNU General Public License
# along with IVRE. If not, see <http://www.gnu.org/licenses/>.
-
+# ARG PIPREQ=requirements-sqlite.txt
FROM debian:12 AS builder

ENV DEBIAN_FRONTEND noninteractive
@@ -21,9 +21,8 @@ ENV DEBIAN_FRONTEND noninteractive
# Install pip then install IVRE
ADD ivre.tar ./
RUN apt-get -q update && \
-    apt-get -qy --no-install-recommends install python3-pip && \
-    pip3 install --break-system-packages /ivre
-
+    apt-get -qy --no-install-recommends install build-essential python3.11-dev libpq-dev python3-pip && \
+    pip3 install --break-system-packages -r "/ivre/requirements-all.txt" /ivre

FROM debian:12
LABEL maintainer="Pierre LALET <pierre@droids-corp.org>"
@@ -45,4 +44,4 @@ COPY --from=builder /usr/local/share/ivre /usr/local/share/ivre
RUN sed -ri 's#$#-docker#' /usr/local/lib/python*/dist-packages/ivre/VERSION && \
sed -ri 's#(VERSION = .*)(['\''"])$#\1-docker\2#' /usr/local/lib/python*/dist-packages/ivre/__init__.py

-RUN echo 'DB = "mongodb://ivredb/"' > /etc/ivre.conf
+RUN echo 'DB = "mongodb://ivredb"' > /etc/ivre.conf
```

### Compose

```yaml
version: "3"
services:
  ivredb:
    image: mongo
    container_name: ivredb
    restart: always
    ports: ["27017:27017"]
    volumes:
      - ivre:/data
      - ./var_lib_mongodb:/data/db
  ivreuwsgi:
    image: ivre/web-uwsgi
    container_name: ivreuwsgi
    restart: always
    depends_on:
      - ivredb
    volumes:
      - ./dokuwiki_data:/var/www/dokuwiki/data
      - ivre:/data
    environment:
      - "IVRE_CONF=/data/ivre.conf"
      - "DEBUG_DB=1"
  ivredoku:
    image: ivre/web-doku
    container_name: ivredoku
    restart: always
    volumes:
      - ./dokuwiki_data:/var/www/dokuwiki/data
    #   - ivre:/data
    # environment:
    #   - "IVRE_CONF=/data/ivre.conf"
    #   - "DEBUG_DB=1"
  ivreweb:
    image: ivre/web
    container_name: ivreweb
    restart: always
    ports: ["80:80"]
    depends_on:
      - ivreuwsgi
      - ivredoku
    volumes:
      - ./dokuwiki_data:/var/www/dokuwiki/data
    #   - ivre:/data
    # environment:
    #   - "IVRE_CONF=/data/ivre.conf"
    #   - "DEBUG_DB=1"
  ivreclient:
    image: ivre/client
    container_name: ivreclient
    depends_on:
      - ivredb
    working_dir: /data
    volumes:
      - ./ivre-share:/ivre-share
      - ivre:/data
    environment:
      - "IVRE_CONF=/data/ivre.conf"
      - "DEBUG_DB=1"
    stdin_open: true
    tty: true

volumes:
  ivre:
    driver: local
    driver_opts:
      type: bind
      device: ${PWD}/docker/data
      o: bind
```

### File Tree

The volumes are in the `./docker`{.verbatim} directory

```sh
ls -al docker docker/data
```

```text
./docker
drwxr-xr-x 13 1000   1000   4096 May 20 13:15 .
drwxr-xr-x 14 1000   1000   4096 May 19 21:34 ..
drwxr-xr-x  2 1000   1000   4096 May 19 11:51 agent
drwxr-xr-x  2 1000   1000   4096 May 19 11:51 base
drwxr-xr-x  2 1000   1000   4096 May 19 19:57 base-local
drwxr-xr-x  2 1000   1000   4096 May 19 11:51 client
drwxr-xr-x  4 1000   1000   4096 May 20 14:59 data
-rw-r--r--  1 1000   1000   2416 May 20 14:51 docker-compose.yml
drwxr-xr-x 14 http http 4096 May 19 12:22 dokuwiki_data
drwxr-xr-x  2 root root 4096 May 19 12:22 ivre-share
-rw-r--r--  1 1000   1000   2807 May 19 11:51 Vagrantfile
drwxr-xr-x  4  999 root 4096 May 20 15:15 var_lib_mongodb
drwxr-xr-x  2 1000   1000   4096 May 19 11:51 web
drwxr-xr-x  2 1000   1000   4096 May 19 11:51 web-doku
drwxr-xr-x  2 1000   1000   4096 May 19 11:51 web-uwsgi

./docker/data
drwxr-xr-x  2 root root  4096 May 20 13:15 configdb
drwxr-xr-x  2 root root  4096 May 20 13:15 db
-rw-rw-rw-  1 root root  2291 May 20 14:59 ivre.conf
-rw-r--r--  1 root root 16384 May 20 14:59 ivre.passive.sqlite
-rw-r--r--  1 root root 16384 May 20 14:53 ivre.sqlite
```
